#pragma once

#define REMOTE_DISPLAY_PORT 4210
#define REMOTE_DISPLAY_HELLO_INTERVAL_MS 1000
#define REMOTE_DISPLAY_OFFLINE_TIMEOUT_MS 5000
#define REMOTE_DISPLAY_MATRIX_REFRESH_MS 50
#define REMOTE_DISPLAY_AP_SSID "RemoteDisplayAP"
#define REMOTE_DISPLAY_AP_PASSWORD "12345678"
#define REMOTE_DISPLAY_WIFI_CONNECT_TIMEOUT_MS 20000
#ifndef REMOTE_DISPLAY_HMAC_ENABLED
#define REMOTE_DISPLAY_HMAC_ENABLED 0
#endif
#ifndef REMOTE_DISPLAY_SECRET
#define REMOTE_DISPLAY_SECRET "change-this-shared-secret"
#endif
